[package]
name = "opencc"
version = "0.1.0"
authors = ["Tony Duan <tony84727@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.54.0"
